### ISSUE TITLE
问个事件监听的文艺

### ISSUE THREAD

**Issue by GavinXu520** [nkbai/go-ethereum-example#2]
事件监听的方式是指，geth那边也是要开启ws的方式才可以用的吧，而且client这边也是必须为ws方式来连接吧？
我本地用了conn, err := ethclient.Dial("http://127.0.0.1:8545")； http的方式就会一直提示我，notifications not supported 换成ws 就是 bad status ，本地的geth启动命令为 ：geth  --rpc  -datadir genesis-block --networkid  1108  console 没有知名rpc相关的参数

**Comment by nkbai** [comment]
是的，监听只能是websocket或者ipc，因为http没法从服务端向客户端推送
